### ISSUE TITLE
Do we have documentation of this package

### ISSUE THREAD

**Issue by dhakerShiv** [One-com/teepee#13]
It is just some questions rather than an issue.
I have two questions - 
1. Do we have documentation of this package.
2. Does it offer anything extra functionally then [axios](https://www.npmjs.com/package/axios) ?

**Comment by gustavnikolaj** [comment]
Unfortunately no, there's not any documentation for this module. The code though has some good comments and is generally pretty understandable, so having a look at that would be my best suggestion for you.
